apiVersion: v2
name: nginx
version: 0.1.0
description: |-
  nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server, originally written by Igor Sysoev.
type: application
keywords:
  - web server
  - http
  - proxy
  - load balancing
home: https://nginx.org/
sources: 
  - https://github.com/nginx/nginx
  - https://github.com/nginxinc/docker-nginx-unprivileged
maintainers:
  - name: Carlos Eduardo Mota
    email: carlos.mota@sgb.gov.br
icon: https://nginx.org/nginx.png
appVersion: "1.25.5"
