apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geonode.database-secret" . }}
type: Opaque
{{- $dbhost := (include "db.hostname" .) }}
stringData:
  {{- with .Values.services.db }}
  # Only for geonode/postgis official images
  {{- if not .external }}
  POSTGRES_PASSWORD: {{ .serverParams.password }}
  POSTGRES_USER: {{ .serverParams.user }}
  POSTGRESQL_MAX_CONNECTIONS: {{ .serverParams.maxConnections | quote }}
  {{- end }}
  {{- end }}

  {{- with .Values.configs.postgres }}
  {{- $databaseUrl :=  printf "postgis://%s:%s@%s:%s/%s" .db.user .db.password $dbhost (.port | toString) .db.name -}}
  {{- $geodatabaseUrl :=  printf "postgis://%s:%s@%s:%s/%s" .geoDb.user .geoDb.password $dbhost (.port | toString) .geoDb.name }}
  # Database runs on same server
  DATABASE_HOST: {{ $dbhost }}
  DATABASE_PORT: {{ .port | quote }}

  # GeoNode database
  GEONODE_DATABASE: {{ .db.name }}
  GEONODE_DATABASE_USER: {{ .db.user }}
  GEONODE_DATABASE_PASSWORD: {{ .db.password }}
  GEONODE_DATABASE_SCHEMA: {{ .db.schema }}

  # GeoNode geodatabase
  GEONODE_GEODATABASE: {{ .geoDb.name }}
  GEONODE_GEODATABASE_USER: {{ .geoDb.user }}
  GEONODE_GEODATABASE_PASSWORD: {{ .geoDb.password }}
  GEONODE_GEODATABASE_SCHEMA: {{ .geoDb.schema }}

  # Django Settings
  DATABASE_URL: {{ $databaseUrl }}
  GEODATABASE_URL: {{ $geodatabaseUrl }}

  # Default django DATABASES key name
  DEFAULT_BACKEND_DATASTORE: datastore

  # Client parameters
  GEONODE_DB_CONN_MAX_AGE: {{ .clientParams.maxAge | quote }}
  GEONODE_DB_CONN_TOUT: {{ .clientParams.timeOut | quote }}
  {{- end }}
