apiVersion: v1
kind: Service
metadata:
  name: {{ include "dspace.fullname" . }}-solr
  labels:
    {{- include "dspace.labels" . | nindent 4 }}
    app.kubernetes.io/component: search-engine
spec:
  type: ClusterIP
  ports:
    - port: 8983
      targetPort: solr-port
      protocol: TCP
      name: solr-port-svc
  selector:
    {{- include "dspace.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: search-engine
