apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "django.labels" . | nindent 4 }}
  name: {{ .Values.services.django.name }}
spec:
  ports:
    - name: wsgi
      port: {{ .Values.services.django.servicePort }}
      targetPort: wsgi
  selector:
    {{- include "django.selectorLabels" . | nindent 6 }}
status:
  loadBalancer: {}
