apiVersion: v2
name: geoserver
version: 0.4.0
description: |-
  GeoServer is an open source server for sharing geospatial data. 
  Designed for interoperability, it publishes data from any major spatial data source using open standards
type: application
keywords:
  - GIS
  - FOSS4G
  - webmap
  - WMS
  - WFS
  - WCS
home: https://geoserver.org/
sources:
  - https://github.com/geoserver/geoserver
  - https://github.com/nds-cprm/geoserver-oci
maintainers:
  - name: Carlos Eduardo Mota
    email: carlos.mota@sgb.gov.br
icon: "https://geoserver.org/img/geoserver-logo.png"
appVersion: "2.24.4"
