{{- if .Values.database.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geonetwork.fullname" . }}-db-credentials
  labels:
    {{- include "geonetwork.labels" . | nindent 4 }}
stringData:
  {{- with .Values.database }}
  GEONETWORK_DB_HOST: {{ .host | quote }}
  GEONETWORK_DB_PORT: {{ .port | quote }}
  GEONETWORK_DB_DATABASE: {{ .name | quote }}
  GEONETWORK_DB_USERNAME: {{ .username | quote }}
  GEONETWORK_DB_PASSWORD: {{ .password | quote }}
  {{- end }}
type: Opaque
{{- end }}
